import { Property } from "./types";

/**
 * Ces biens de démonstration s'affichent tant qu'aucune base Supabase
 * n'est connectée (voir README.md, étape 4). Une fois Supabase configuré,
 * les vrais biens ajoutés depuis /admin remplacent automatiquement cette liste.
 */
export const demoProperties: Property[] = [
  {
    id: "demo-1",
    slug: "maison-colombages-centre-colmar",
    title: "Maison à colombages rénovée, centre historique",
    kind: "vente",
    category: "Maison",
    price: 495000,
    city: "Colmar",
    postal_code: "68000",
    surface_m2: 140,
    rooms: 6,
    bedrooms: 4,
    dpe: "C",
    ges: "B",
    description:
      "À deux pas de la Petite Venise, cette maison à colombages entièrement rénovée offre de belles pièces de vie, une cour intérieure privative et des matériaux d'origine préservés (poutres apparentes, tomettes). Cuisine ouverte, quatre chambres, bureau et cave voûtée.",
    highlights: ["Cour privative", "Poutres apparentes", "Cave voûtée", "Proche centre historique"],
    status: "disponible",
    featured: true,
    cover_color: "#8B5A34",
    created_at: "2026-06-01T09:00:00Z",
  },
  {
    id: "demo-2",
    slug: "appartement-lumineux-quartier-gare",
    title: "Appartement traversant lumineux, quartier gare",
    kind: "vente",
    category: "Appartement",
    price: 219000,
    city: "Colmar",
    postal_code: "68000",
    surface_m2: 78,
    rooms: 4,
    bedrooms: 2,
    dpe: "D",
    ges: "D",
    description:
      "Au 3ᵉ étage avec ascenseur, cet appartement traversant bénéficie d'une double exposition est-ouest. Séjour de 28 m², deux chambres, balcon filant et place de parking privative en sous-sol.",
    highlights: ["Ascenseur", "Double exposition", "Parking privatif", "Proche gare TGV"],
    status: "disponible",
    featured: true,
    cover_color: "#5F6F52",
    created_at: "2026-06-05T09:00:00Z",
  },
  {
    id: "demo-3",
    slug: "villa-contemporaine-piscine-wintzenheim",
    title: "Villa contemporaine avec piscine, Wintzenheim",
    kind: "vente",
    category: "Maison",
    price: 690000,
    city: "Wintzenheim",
    postal_code: "68920",
    surface_m2: 210,
    rooms: 7,
    bedrooms: 5,
    dpe: "A",
    ges: "A",
    description:
      "Construction 2022 basse consommation, cette villa d'architecte offre de vastes volumes baignés de lumière, une piscine à débordement et un jardin paysager de 1200 m². Domotique intégrale.",
    highlights: ["Piscine à débordement", "Domotique", "BBC 2022", "Jardin 1200 m²"],
    status: "disponible",
    featured: true,
    cover_color: "#202B38",
    created_at: "2026-06-10T09:00:00Z",
  },
  {
    id: "demo-4",
    slug: "studio-meuble-hyper-centre",
    title: "Studio meublé, hyper-centre",
    kind: "location",
    category: "Appartement",
    price: 480,
    city: "Colmar",
    postal_code: "68000",
    surface_m2: 24,
    rooms: 1,
    bedrooms: 0,
    dpe: "D",
    ges: "C",
    description:
      "Studio meublé et fonctionnel en plein cœur de Colmar, idéal étudiant ou jeune actif. Kitchenette équipée, salle d'eau rénovée, charges comprises.",
    highlights: ["Meublé", "Charges comprises", "Hyper-centre", "Disponible immédiatement"],
    status: "disponible",
    featured: false,
    cover_color: "#6E2A34",
    created_at: "2026-06-12T09:00:00Z",
  },
  {
    id: "demo-5",
    slug: "t3-avec-balcon-horbourg-wihr",
    title: "T3 avec balcon, résidence récente",
    kind: "location",
    category: "Appartement",
    price: 790,
    city: "Horbourg-Wihr",
    postal_code: "68180",
    surface_m2: 65,
    rooms: 3,
    bedrooms: 2,
    dpe: "B",
    ges: "A",
    description:
      "Dans une résidence 2021, T3 avec balcon plein sud, cave et place de parking. Cuisine équipée, chauffage collectif performant.",
    highlights: ["Résidence 2021", "Balcon plein sud", "Cave + parking", "Cuisine équipée"],
    status: "disponible",
    featured: false,
    cover_color: "#8B5A34",
    created_at: "2026-06-14T09:00:00Z",
  },
  {
    id: "demo-6",
    slug: "terrain-a-batir-ingersheim",
    title: "Terrain à bâtir viabilisé, Ingersheim",
    kind: "vente",
    category: "Terrain",
    price: 165000,
    city: "Ingersheim",
    postal_code: "68000",
    surface_m2: 550,
    rooms: 0,
    bedrooms: 0,
    dpe: "G",
    ges: "G",
    description:
      "Terrain plat et viabilisé de 550 m² dans un lotissement calme, exposition sud-ouest, libre de constructeur. CU opérationnel disponible.",
    highlights: ["Viabilisé", "Libre de constructeur", "Exposition sud-ouest", "CU opérationnel"],
    status: "disponible",
    featured: false,
    cover_color: "#5F6F52",
    created_at: "2026-06-16T09:00:00Z",
  },
];

export function getDemoPropertyBySlug(slug: string) {
  return demoProperties.find((p) => p.slug === slug) ?? null;
}
