import { Property } from "./types";

/**
 * Ces biens de démonstration s'affichent tant qu'aucune base Supabase
 * n'est connectée (voir README.md, étape 4). Une fois Supabase configuré,
 * les vrais biens ajoutés depuis /admin remplacent automatiquement cette liste.
 */
export const demoProperties: Property[] = [
  {
    id: "demo-1",
    slug: "villa-standing-cocody-riviera",
    title: "Villa de standing avec piscine, Cocody Riviera",
    kind: "vente",
    category: "Maison",
    price: 185000000,
    city: "Cocody",
    postal_code: "Abidjan",
    surface_m2: 320,
    rooms: 7,
    bedrooms: 5,
    dpe: "B",
    ges: "B",
    description:
      "Dans un quartier résidentiel calme de Cocody Riviera, cette villa contemporaine offre de vastes volumes, une piscine, un jardin paysager et un système de sécurité 24h/24. Climatisation centralisée, groupe électrogène et forage inclus.",
    highlights: ["Piscine", "Groupe électrogène", "Forage d'eau", "Quartier sécurisé", "Climatisation centralisée"],
    status: "disponible",
    featured: true,
    cover_color: "#8B5A34",
    photos: [],
    created_at: "2026-06-01T09:00:00Z",
  },
  {
    id: "demo-2",
    slug: "appartement-standing-plateau",
    title: "Appartement 3 pièces avec vue, Le Plateau",
    kind: "vente",
    category: "Appartement",
    price: 65000000,
    city: "Plateau",
    postal_code: "Abidjan",
    surface_m2: 95,
    rooms: 4,
    bedrooms: 2,
    dpe: "C",
    ges: "C",
    description:
      "Au 8ᵉ étage d'une résidence sécurisée du Plateau, cet appartement offre une vue dégagée sur la lagune. Ascenseur, parking privatif, gardiennage permanent.",
    highlights: ["Vue lagune", "Ascenseur", "Parking privatif", "Gardiennage 24h/24"],
    status: "disponible",
    featured: true,
    cover_color: "#5F6F52",
    photos: [],
    created_at: "2026-06-05T09:00:00Z",
  },
  {
    id: "demo-3",
    slug: "villa-moderne-angre",
    title: "Villa moderne 4 chambres, Angré",
    kind: "vente",
    category: "Maison",
    price: 98000000,
    city: "Angré",
    postal_code: "Abidjan",
    surface_m2: 260,
    rooms: 6,
    bedrooms: 4,
    dpe: "B",
    ges: "A",
    description:
      "Construction récente à Angré 8ᵉ Tranche, cette villa moderne dispose d'un salon double, d'une cuisine équipée, d'une cour arborée et d'un espace pour un logement de gardien.",
    highlights: ["Construction récente", "Logement gardien", "Cour arborée", "Cuisine équipée"],
    status: "disponible",
    featured: true,
    cover_color: "#202B38",
    photos: [],
    created_at: "2026-06-10T09:00:00Z",
  },
  {
    id: "demo-4",
    slug: "studio-meuble-marcory",
    title: "Studio meublé, Marcory Résidentiel",
    kind: "location",
    category: "Appartement",
    price: 180000,
    city: "Marcory",
    postal_code: "Abidjan",
    surface_m2: 28,
    rooms: 1,
    bedrooms: 0,
    dpe: "D",
    ges: "C",
    description:
      "Studio meublé et climatisé dans une résidence calme de Marcory, idéal jeune actif ou expatrié. Cuisine équipée, eau et électricité inclus dans un forfait mensuel sur demande.",
    highlights: ["Meublé", "Climatisé", "Résidence sécurisée", "Disponible immédiatement"],
    status: "disponible",
    featured: false,
    cover_color: "#6E2A34",
    photos: [],
    created_at: "2026-06-12T09:00:00Z",
  },
  {
    id: "demo-5",
    slug: "appartement-3-pieces-riviera-palmeraie",
    title: "Appartement 3 pièces, Riviera Palmeraie",
    kind: "location",
    category: "Appartement",
    price: 350000,
    city: "Riviera",
    postal_code: "Abidjan",
    surface_m2: 85,
    rooms: 3,
    bedrooms: 2,
    dpe: "C",
    ges: "B",
    description:
      "Dans une résidence fermée proche de Playce Palmeraie, appartement lumineux avec balcon, parking et générateur commun. Idéal famille ou colocation.",
    highlights: ["Proche Playce Palmeraie", "Résidence fermée", "Balcon", "Parking"],
    status: "disponible",
    featured: false,
    cover_color: "#8B5A34",
    photos: [],
    created_at: "2026-06-14T09:00:00Z",
  },
  {
    id: "demo-6",
    slug: "terrain-a-batir-bingerville",
    title: "Terrain à bâtir viabilisé, Bingerville",
    kind: "vente",
    category: "Terrain",
    price: 25000000,
    city: "Bingerville",
    postal_code: "Abidjan",
    surface_m2: 600,
    rooms: 0,
    bedrooms: 0,
    dpe: "G",
    ges: "G",
    description:
      "Terrain plat et viabilisé de 600 m² dans un lotissement en plein développement à Bingerville, titre foncier disponible, idéal pour projet résidentiel.",
    highlights: ["Titre foncier disponible", "Viabilisé", "Zone en développement", "Libre de constructeur"],
    status: "disponible",
    featured: false,
    cover_color: "#5F6F52",
    photos: [],
    created_at: "2026-06-16T09:00:00Z",
  },
];

export function getDemoPropertyBySlug(slug: string) {
  return demoProperties.find((p) => p.slug === slug) ?? null;
}
